Repository Ruka-CFW/rk3128-cfw, pull requests merged in 2021-06, with the labels that each got.

#36 Add issue template for bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#37 Fix links to Rockchip repositories
  doc/install.md
  doc/install_es.md
  doc/install_it.md
Labels: bug, documentation

#43 added backup process ESP and ENG
  doc/install.md
  doc/install_es.md
Labels: documentation, help wanted
